proiect/jobs/urls.py
from django.urls import path

from jobs import views

app_name = "jobs"

urlpatterns = [
    path("", views.JobsView.as_view(), name="lista_joburi"),
    path('adaugare/', views.CreateJobsView.as_view(), name='adauga'),
    path('<int:pk>/update/', views.UpdateJobsView.as_view(), name='modifica'),
    path('<int:pk>/stergere/', views.delete_jobs, name='sterge'),
    path('<int:pk>/activeaza/', views.activate_jobs, name='activeaza'),
]

proiect/proiect/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('locations/', include('aplicatie1.urls')),
    path("companies/", include("aplicatie2.urls")),
    path("profile/", include("user_profile.urls")),
    path("api/", include("myapi.urls")),
    path("jobs/", include("jobs.urls"))

]

proiect/jobs/models.py
from django.db import models

type = (("FULLTIME", "FULLTIME"), ("PART-TIME", "PART-TIME"), ("HIBRID", "HIBRID"))


# Create your models here.
class Jobs(models.Model):
    type = models.CharField(max_length=100, choices=type)
    title = models.CharField(max_length=150)
    url = models.CharField(max_length=100)
    description = models.TextField()
    how_to_apply = models.TextField()
    active = models.BooleanField(default=1)

    def __str__(self):
        return f"{self.title} - {self.description}"

proiect/jobs/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
# Create your views here.
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView

from jobs.models import Jobs


class JobsView(LoginRequiredMixin, ListView):
    model = Jobs
    template_name = "jobs/jobs_index.html"
    paginate_by = 5


class CreateJobsView(LoginRequiredMixin, CreateView):
    model = Jobs
    fields = ['type', 'title', "url", "description", "how_to_apply"]
    template_name = 'jobs/jobs_form.html'

    def get_success_url(self):
        return reverse('jobs:lista_joburi')


class UpdateJobsView(LoginRequiredMixin, UpdateView):
    model = Jobs
    fields = ['type', 'title', "url", "description", "how_to_apply", "active"]
    template_name = 'jobs/jobs_form.html'

    def get_success_url(self):
        return reverse('jobs:lista_joburi')


@login_required
def delete_jobs(request, pk):
    Jobs.objects.filter(id=pk).update(active=0)
    return redirect("jobs:lista_joburi")


@login_required
def activate_jobs(request, pk):
    Jobs.objects.filter(id=pk).update(active=1)
    return redirect("jobs:lista_joburi")

proiect/templates/jobs/jobs_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label }} {{ field }}<br>
        {% endfor %}
        <button type="submit">Salveaza</button>
    </form>
{% endblock %}

proiect/templates/jobs/jobs_index.html
{% extends 'base.html' %}
{% block content %}
    <a href="{% url 'jobs:adauga' %}" class="btn btn-success">Adauga job</a>

    <table class="table">
        <thead>
        <tr>
            <th>Index</th>
            <th>Type</th>
            <th>Title</th>
            <th>Url</th>
            <th>Description</th>
            <th>How to apply</th>
            <th>Active</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for item in jobs_list %}
            <tr>
                <td>{{ forloop.counter0|add:page_obj.start_index }}</td>
                <td>{{ item.type }}</td>
                <td>{{ item.title }}</td>
                <td>{{ item.url }}</td>
                <td>{{ item.description }}</td>
                <td>{{ item.how_to_apply }}</td>
                <td>
                    {% if item.active == 1 %}
                        <span>Active</span>
                    {% else %}
                        <span>Inactive</span>
                    {% endif %}
                </td>
                <td>
                    <a href="{% url 'jobs:modifica' item.id %}" class="btn btn-success">Modifica</a>
                    {% if item.active == 1 %}
                        <a href="{% url 'jobs:sterge' item.id %}" class="btn btn-danger">Sterge</a>
                    {% else %}
                        <a href="{% url 'jobs:activeaza' item.id %}" class="btn btn-info">Activeaza</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="d-flex justify-content-center">
        {% if is_paginated %}
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li><a class="btn" href="?page={{ page_obj.previous_page_number }}"><<</a></li>
                {% else %}
                    <li class="disabled btn"><span><<</span></li>
                {% endif %}
                {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li class="active btn btn-info"><span>{{ i }}<span class="sr-only">(curent)</span></span></li>
                    {% else %}
                        <li><a class="btn" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li><a class="btn" href="?page={{ page_obj.next_page_number }}">>></a></li>
                {% else %}
                    <li class="disabled btn"><span><<</span></li>
                {% endif %}
                <span class="align-items-center pt centrare verticala">Showing {{ page_obj.start_index }} - {{ page_obj.end_index }} of {{ page_obj.paginator.count }}</span>
            </ul>
        {% endif %}
    </div>
{% endblock %}