proiect/aplicatie1/urls.py
from django.urls import path

from aplicatie1 import views

app_name = "locations"

urlpatterns = [
    path("", views.LocationsView.as_view(), name="lista_locatii"),
    path('adaugare/', views.CreateLocationView.as_view(), name='adauga'),
    path('<int:pk>/update/', views.UpdateLocationView.as_view(), name='modifica'),
    path('<int:pk>/stergere/', views.delete_location, name='sterge'),
    path('<int:pk>/activeaza/', views.activate_location, name='activeaza'),
]

proiect/aplicatie2/urls.py
from django.urls import path

from aplicatie2 import views

app_name = "companies"

urlpatterns = [
    path("", views.CompaniesView.as_view(), name="companies_list"),
    path("add/", views.CreateCompanyView.as_view(), name="add"),
    path("<int:pk>/update/", views.UpdateCompaniesView.as_view(), name="update"),
    path("<int:pk>/delete/", views.delete_company, name="delete"),
    path("<int:pk>/activate", views.activate_company, name="activate"),
]

proiect/jobs/urls.py
from django.urls import path

from jobs import views

app_name = "jobs"

urlpatterns = [
    path("", views.JobsView.as_view(), name="lista_joburi"),
    path('adaugare/', views.CreateJobsView.as_view(), name='adauga'),
    path('<int:pk>/update/', views.UpdateJobsView.as_view(), name='modifica'),
    path('<int:pk>/stergere/', views.delete_jobs, name='sterge'),
    path('<int:pk>/activeaza/', views.activate_jobs, name='activeaza'),
]

proiect/proiect/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('locations/', include('aplicatie1.urls')),
    path("companies/", include("aplicatie2.urls")),
    path("profile/", include("user_profile.urls")),
    path("api/", include("myapi.urls")),
    path("jobs/", include("jobs.urls"))

]

proiect/user_profile/urls.py
from django.urls import path

from user_profile import views

app_name = "userprofile"

urlpatterns = [
    path("start_timesheet/", views.new_timesheet, name="start_pontaj"),
    path("stop_timesheet/", views.stop_timesheet, name="stop_pontaj"),
]

proiect/templates/base.html
<html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <nav>
                <a class="btn" href="/admin">Admin</a>
                {% if request.user.is_authenticated %}
                    <a class="btn" href="{% url 'locations:lista_locatii' %}">Locatii</a>
                    <a class="btn" href="{% url "companies:companies_list" %}">Companies</a>
                    <a class="btn" href="{% url "jobs:lista_joburi" %}">Joburi</a>
                    <a class="btn" href="{% url 'logout' %}">Logout</a>
                    <span>Hi, {{ request.user.username|upper }}</span>
                    {% if ready_to_work is False %}
                        <a href="{% url "userprofile:stop_pontaj" %}" class="btn btn-danger">Oprire Pontaj</a>
                    {% else %}
                        <a href="{% url "userprofile:start_pontaj" %}" class="btn btn-success">Pornire Pontaj</a>
                    {% endif %}

                {% endif %}
            </nav>
        </div>
    </div>
</div>
{% block content %}
{% endblock %}
</body>

</html>