proiect/aplicatie1/urls.py
from django.urls import path

from aplicatie1 import views

app_name = "locations"

urlpatterns = [
    path("", views.LocationsView.as_view(), name="lista_locatii"),
    path('adaugare/', views.CreateLocationView.as_view(), name='adauga'),
    path('<int:pk>/update/', views.UpdateLocationView.as_view(), name='modifica'),
    path('<int:pk>/stergere/', views.delete_location, name='sterge'),
    path('<int:pk>/activeaza/', views.activate_location, name='activeaza'),
]

proiect/jobs/urls.py
from django.urls import path

from jobs import views

app_name = "jobs"

urlpatterns = [
    path("", views.JobsView.as_view(), name="lista_joburi"),
    path('adaugare/', views.CreateJobsView.as_view(), name='adauga'),
    path('<int:pk>/update/', views.UpdateJobsView.as_view(), name='modifica'),
    path('<int:pk>/stergere/', views.delete_jobs, name='sterge'),
    path('<int:pk>/activeaza/', views.activate_jobs, name='activeaza'),
]

proiect/proiect/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('locations/', include('aplicatie1.urls')),
    path("companies/", include("aplicatie2.urls")),
    path("profile/", include("user_profile.urls")),
    path("api/", include("myapi.urls")),
    path("jobs/", include("jobs.urls"))

]

proiect/aplicatie1/models.py
from django.db import models


# Create your models here.
class Locations(models.Model):
    city = models.CharField(max_length=100)
    country = models.CharField(max_length=150)
    active = models.BooleanField(default=1)

    def __str__(self):
        return f"{self.city} - {self.country}"

proiect/aplicatie1/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView

from aplicatie1.models import Locations


class LocationsView(LoginRequiredMixin, ListView):
    model = Locations
    template_name = "aplicatie1/locations_index.html"
    paginate_by = 5


class CreateLocationView(LoginRequiredMixin, CreateView):
    model = Locations
    fields = ['city', 'country']
    template_name = 'aplicatie1/locations_form.html'

    def get_success_url(self):
        return reverse('locations:lista_locatii')


class UpdateLocationView(LoginRequiredMixin, UpdateView):
    model = Locations
    fields = ['city', 'country']
    template_name = 'aplicatie1/locations_form.html'

    def get_success_url(self):
        return reverse('locations:lista_locatii')


@login_required
def delete_location(request, pk):
    Locations.objects.filter(id=pk).update(active=0)
    return redirect("locations:lista_locatii")


@login_required
def activate_location(request, pk):
    Locations.objects.filter(id=pk).update(active=1)
    return redirect("locations:lista_locatii")

proiect/templates/aplicatie1/locations_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label }} {{ field }}<br>
        {% endfor %}
        <button type="submit">Salveaza</button>
    </form>
{% endblock %}

proiect/templates/aplicatie1/locations_index.html
{% extends 'base.html' %}
{% block content %}
    <a href="{% url 'locations:adauga' %}" class="btn btn-success">Adauga locatie</a>

    <table class="table">
        <thead>
        <tr>
            <th>Index</th>
            <th>City</th>
            <th>Country</th>
            <th>Stare</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for item in locations_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ item.city }}</td>
                <td>{{ item.country }}</td>
                <td>
                    {% if item.active == 1 %}
                        <span>Active</span>
                    {% else %}
                        <span>Inactive</span>
                    {% endif %}
                </td>
                <td>
                    <a href="{% url 'locations:modifica' item.id %}" class="btn btn-success">Modifica</a>
                    {% if item.active == 1 %}
                        <a href="{% url 'locations:sterge' item.id %}" class="btn btn-danger">Sterge</a>
                    {% else %}
                        <a href="{% url 'locations:activeaza' item.id %}" class="btn btn-info">Activeaza</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}