proiect/aplicatie2/urls.py
from django.urls import path

from aplicatie2 import views

app_name = "companies"

urlpatterns = [
    path("", views.CompaniesView.as_view(), name="companies_list"),
    path("add/", views.CreateCompanyView.as_view(), name="add"),
    path("<int:pk>/update/", views.UpdateCompaniesView.as_view(), name="update"),
    path("<int:pk>/delete/", views.delete_company, name="delete"),
    path("<int:pk>/activate", views.activate_company, name="activate"),
]

proiect/jobs/urls.py
from django.urls import path

from jobs import views

app_name = "jobs"

urlpatterns = [
    path("", views.JobsView.as_view(), name="lista_joburi"),
    path('adaugare/', views.CreateJobsView.as_view(), name='adauga'),
    path('<int:pk>/update/', views.UpdateJobsView.as_view(), name='modifica'),
    path('<int:pk>/stergere/', views.delete_jobs, name='sterge'),
    path('<int:pk>/activeaza/', views.activate_jobs, name='activeaza'),
]

proiect/proiect/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('locations/', include('aplicatie1.urls')),
    path("companies/", include("aplicatie2.urls")),
    path("profile/", include("user_profile.urls")),
    path("api/", include("myapi.urls")),
    path("jobs/", include("jobs.urls"))

]

proiect/aplicatie2/models.py
from django.db import models
company_type = (("SRL", "S.R.L"), ("SA", "S.A"))


class Companies(models.Model):
    name = models.CharField(max_length=100)
    website = models.CharField(max_length=50)
    company_type = models.CharField(max_length=10, choices=company_type)
    active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.name}-{self.website}-{self.company_type}"

proiect/aplicatie2/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from aplicatie2.models import Companies


class CompaniesView(LoginRequiredMixin, ListView):
    model = Companies
    template_name = "aplicatie2/companies_index.html"


class CreateCompanyView(LoginRequiredMixin, CreateView):
    model = Companies
    fields = ["name", "website", "company_type"]
    template_name = "aplicatie2/company_form.html"

    def get_success_url(self):
        return reverse('companies:companies_list')


class UpdateCompaniesView(LoginRequiredMixin, UpdateView):
    model = Companies
    fields = ["name", "website", "company_type"]
    template_name = "aplicatie2/company_form.html"

    def get_success_url(self):
        return reverse('companies:companies_list')


@login_required
def delete_company(request, pk):
    Companies.objects.filter(id=pk).update(active=0)
    return redirect("companies:companies_list")

@login_required
def activate_company(request, pk):
    Companies.objects.filter(id=pk).update(active=1)
    return redirect("companies:companies_list")

proiect/templates/aplicatie2/companies_index.html
{% extends "base.html" %}
{% block content %}
    <a href="{% url "companies:add" %}" class="btn btn-success">Adauga companie</a>
    <table class="table">
        <thead>
        <tr>
            <th>Index</th>
            <th>Name</th>
            <th>Website</th>
            <th>Company type</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for item in companies_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ item.name }}</td>
                <td>{{ item.website }}</td>
                <td>{{ item.company_type }}</td>
                <td>
                    {% if item.active == 1 %}
                        <span>Active</span>
                    {% else %}
                        <span>Inactive</span>
                    {% endif %}
                </td>
                <td>
                    <a href="{% url 'companies:update' item.id %}" class="btn btn-success">Modifica</a>
                    {% if item.active == 1 %}
                        <a href="{% url 'companies:delete' item.id %}" class="btn btn-danger">Sterge</a>
                    {% else %}
                        <a href="{% url 'companies:activate' item.id %}" class="btn btn-info">Activeaza</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

proiect/templates/aplicatie2/company_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label }} {{ field }}<br>
        {% endfor %}
        <button type="submit">Salveaza</button>
    </form>
{% endblock %}